version: "2"

services:
  loraserver:
    image: 123leej/net-server:latest
    volumes:
      - ./configuration/loraserver:/etc/loraserver
 
  appserver:
    image: 123leej/app-server:latest
    ports:
      - 8080:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: 123leej/gw-bridge:latest
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge
  
  postgresql:
    image: 123leej/postgres:latest
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    ports:
      - 6379
    image: 123leej/redis:latest
    volumes:
      - ./data/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883


